// Auto-generated type declarations for model prices data
// Do not edit this file manually - it will be overwritten by the download script

export declare const modelPricesData: Record<string, any>;
